# Twilio IAM API requires application/x-www-form-urlencoded POST data.
# When Policy is invalid or permissions do not exist, Twilio returns 400 with a detailed JSON error body.
locals {
  twilio_readonly_policy = {
    allow = [
      "/twilio/billing/usage/read",
      "/twilio/conversations-classic/configuration.addresses/list",
      "/twilio/conversations-classic/configuration.addresses/read",
      "/twilio/conversations-classic/configuration.webhooks/list",
      "/twilio/conversations-classic/configuration/read",
      "/twilio/conversations-classic/conversations/list",
      "/twilio/conversations-classic/conversations/read",
      "/twilio/conversations-classic/credentials/list",
      "/twilio/conversations-classic/credentials/read",
      "/twilio/conversations-classic/messages.metadata/read",
      "/twilio/conversations-classic/messages.receipts/list",
      "/twilio/conversations-classic/messages.receipts/read",
      "/twilio/conversations-classic/messages/list",
      "/twilio/conversations-classic/messages/read",
      "/twilio/conversations-classic/participant-conversations/list",
      "/twilio/conversations-classic/participants/list",
      "/twilio/conversations-classic/participants/read",
      "/twilio/conversations-classic/roles/list",
      "/twilio/conversations-classic/roles/read",
      "/twilio/conversations-classic/services.bindings/list",
      "/twilio/conversations-classic/services.bindings/read",
      "/twilio/conversations-classic/services.configuration.notifications/read",
      "/twilio/conversations-classic/services/list",
      "/twilio/conversations-classic/services/read",
      "/twilio/conversations-classic/users.conversations/list",
      "/twilio/conversations-classic/users.conversations/read",
      "/twilio/conversations-classic/users/list",
      "/twilio/conversations-classic/users/read",
      "/twilio/conversations-classic/webhooks/list",
      "/twilio/conversations-classic/webhooks/read",
      "/twilio/event-streams/event-type/list",
      "/twilio/event-streams/event-type/read",
      "/twilio/event-streams/schema.version/list",
      "/twilio/event-streams/schema.version/read",
      "/twilio/event-streams/schema/read",
      "/twilio/event-streams/sink/list",
      "/twilio/event-streams/sink/read",
      "/twilio/event-streams/subscription.subscribed-event/list",
      "/twilio/event-streams/subscription.subscribed-event/read",
      "/twilio/event-streams/subscription/list",
      "/twilio/event-streams/subscription/read",
      "/twilio/flex/flex-instance/read",
      "/twilio/iam/accounts/list",
      "/twilio/iam/accounts/read",
      "/twilio/iam/api-keys/list",
      "/twilio/iam/api-keys/read",
      "/twilio/iam/credentials-aws/list",
      "/twilio/iam/credentials-aws/read",
      "/twilio/iam/public-keys/list",
      "/twilio/iam/public-keys/read",
      "/twilio/lookup/phone-numbers/read",
      "/twilio/messaging/content-templates/list",
      "/twilio/messaging/content-templates/read",
      "/twilio/messaging/deactivations/list",
      "/twilio/messaging/messages.media/list",
      "/twilio/messaging/messages.media/read",
      "/twilio/messaging/messages/list",
      "/twilio/messaging/messages/read",
      "/twilio/messaging/pricing/list",
      "/twilio/messaging/pricing/read",
      "/twilio/messaging/services.alphasenders/list",
      "/twilio/messaging/services.alphasenders/read",
      "/twilio/messaging/services.channelsenders/list",
      "/twilio/messaging/services.channelsenders/read",
      "/twilio/messaging/services.phonenumbers/list",
      "/twilio/messaging/services.phonenumbers/read",
      "/twilio/messaging/services.shortcodes/list",
      "/twilio/messaging/services.shortcodes/read",
      "/twilio/messaging/services.usa2p-campaign/list",
      "/twilio/messaging/services.usa2p-campaign/read",
      "/twilio/messaging/services.usa2p-usecase/list",
      "/twilio/messaging/services/list",
      "/twilio/messaging/services/read",
      "/twilio/messaging/whatsapp-senders/list",
      "/twilio/messaging/whatsapp-senders/read",
      "/twilio/monitor/alerts/list",
      "/twilio/monitor/alerts/read",
      "/twilio/monitor/events/list",
      "/twilio/monitor/events/read",
      "/twilio/phone-numbers/active-numbers/list",
      "/twilio/phone-numbers/active-numbers/read",
      "/twilio/phone-numbers/available-numbers/list",
      "/twilio/phone-numbers/incoming-phone-numbers/list",
      "/twilio/phone-numbers/incoming-phone-numbers/read",
      "/twilio/phone-numbers/regulatory-compliance.bundle-copies/list",
      "/twilio/phone-numbers/regulatory-compliance.bundles/list",
      "/twilio/phone-numbers/regulatory-compliance.bundles/read",
      "/twilio/phone-numbers/regulatory-compliance.end-users-types/list",
      "/twilio/phone-numbers/regulatory-compliance.end-users-types/read",
      "/twilio/phone-numbers/regulatory-compliance.end-users/list",
      "/twilio/phone-numbers/regulatory-compliance.end-users/read",
      "/twilio/phone-numbers/regulatory-compliance.evaluations/list",
      "/twilio/phone-numbers/regulatory-compliance.evaluations/read",
      "/twilio/phone-numbers/regulatory-compliance.item-assignments/list",
      "/twilio/phone-numbers/regulatory-compliance.item-assignments/read",
      "/twilio/phone-numbers/regulatory-compliance.regulations/list",
      "/twilio/phone-numbers/regulatory-compliance.regulations/read",
      "/twilio/phone-numbers/regulatory-compliance.supporting-documents-types/list",
      "/twilio/phone-numbers/regulatory-compliance.supporting-documents-types/read",
      "/twilio/phone-numbers/regulatory-compliance.supporting-documents/list",
      "/twilio/phone-numbers/regulatory-compliance.supporting-documents/read",
      "/twilio/serverless/assets.versions/list",
      "/twilio/serverless/assets.versions/read",
      "/twilio/serverless/assets/list",
      "/twilio/serverless/assets/read",
      "/twilio/serverless/builds.status/read",
      "/twilio/serverless/builds/list",
      "/twilio/serverless/builds/read",
      "/twilio/serverless/deployments/list",
      "/twilio/serverless/deployments/read",
      "/twilio/serverless/environments/list",
      "/twilio/serverless/environments/read",
      "/twilio/serverless/functions.versions.code/read",
      "/twilio/serverless/functions.versions/list",
      "/twilio/serverless/functions.versions/read",
      "/twilio/serverless/functions/list",
      "/twilio/serverless/functions/read",
      "/twilio/serverless/logs/list",
      "/twilio/serverless/logs/read",
      "/twilio/serverless/services/list",
      "/twilio/serverless/services/read",
      "/twilio/serverless/variables/list",
      "/twilio/serverless/variables/read",
      "/twilio/studio/executions.context/read",
      "/twilio/studio/executions.steps/list",
      "/twilio/studio/executions.steps/read",
      "/twilio/studio/executions/list",
      "/twilio/studio/executions/read",
      "/twilio/studio/flows.revisions/list",
      "/twilio/studio/flows.revisions/read",
      "/twilio/studio/flows/list",
      "/twilio/studio/flows/read",
      "/twilio/studio/test-users/read",
      "/twilio/taskrouter/workspaces.activities/list",
      "/twilio/taskrouter/workspaces.activities/read",
      "/twilio/taskrouter/workspaces.cumulative-statistics/list",
      "/twilio/taskrouter/workspaces.events/list",
      "/twilio/taskrouter/workspaces.events/read",
      "/twilio/taskrouter/workspaces.real-time-statistics/list",
      "/twilio/taskrouter/workspaces.statistics/list",
      "/twilio/taskrouter/workspaces.task-channels/list",
      "/twilio/taskrouter/workspaces.task-channels/read",
      "/twilio/taskrouter/workspaces.task-queue.bulk-real-time-statistics/list",
      "/twilio/taskrouter/workspaces.task-queue.real-time-statistics/list",
      "/twilio/taskrouter/workspaces.task-queues.cumulative-statistics/list",
      "/twilio/taskrouter/workspaces.task-queues.instance-statistics/list",
      "/twilio/taskrouter/workspaces.task-queues.statistics/list",
      "/twilio/taskrouter/workspaces.task-queues/list",
      "/twilio/taskrouter/workspaces.task-queues/read",
      "/twilio/taskrouter/workspaces.tasks.reservations/list",
      "/twilio/taskrouter/workspaces.tasks.reservations/read",
      "/twilio/taskrouter/workspaces.tasks/list",
      "/twilio/taskrouter/workspaces.tasks/read",
      "/twilio/taskrouter/workspaces.workers.channels/list",
      "/twilio/taskrouter/workspaces.workers.channels/read",
      "/twilio/taskrouter/workspaces.workers.cumulative-statistics/list",
      "/twilio/taskrouter/workspaces.workers.instance-statistics/list",
      "/twilio/taskrouter/workspaces.workers.real-time-statistics/list",
      "/twilio/taskrouter/workspaces.workers.reservations/list",
      "/twilio/taskrouter/workspaces.workers.reservations/read",
      "/twilio/taskrouter/workspaces.workers.statistics/list",
      "/twilio/taskrouter/workspaces.workers/list",
      "/twilio/taskrouter/workspaces.workers/read",
      "/twilio/taskrouter/workspaces.workflows.cumulative-statistics/list",
      "/twilio/taskrouter/workspaces.workflows.real-time-statistics/list",
      "/twilio/taskrouter/workspaces.workflows.statistics/list",
      "/twilio/taskrouter/workspaces.workflows/list",
      "/twilio/taskrouter/workspaces.workflows/read",
      "/twilio/taskrouter/workspaces/list",
      "/twilio/taskrouter/workspaces/read",
      "/twilio/verify/access-token/read",
      "/twilio/verify/bucket/list",
      "/twilio/verify/bucket/read",
      "/twilio/verify/challenge/list",
      "/twilio/verify/challenge/read",
      "/twilio/verify/entity/list",
      "/twilio/verify/entity/read",
      "/twilio/verify/factor/list",
      "/twilio/verify/factor/read",
      "/twilio/verify/rate-limit/list",
      "/twilio/verify/rate-limit/read",
      "/twilio/verify/safelist/read",
      "/twilio/verify/service/list",
      "/twilio/verify/service/read",
      "/twilio/verify/verification-attempt/list",
      "/twilio/verify/verification-attempt/read",
      "/twilio/verify/verification-attempts-summary/read",
      "/twilio/verify/verification-template/list",
      "/twilio/verify/verification/read",
      "/twilio/verify/webhook/list",
      "/twilio/verify/webhook/read",
      "/twilio/video/compositions/compositions.composition-hooks/list",
      "/twilio/video/compositions/compositions.composition-hooks/read",
      "/twilio/video/compositions/compositions.composition-settings/read",
      "/twilio/video/compositions/compositions/list",
      "/twilio/video/compositions/compositions/read",
      "/twilio/video/recordings/recordings.recording-settings/read",
      "/twilio/video/recordings/recordings/list",
      "/twilio/video/recordings/recordings/read",
      "/twilio/video/rooms/rooms.participants.published-tracks/list",
      "/twilio/video/rooms/rooms.participants.published-tracks/read",
      "/twilio/video/rooms/rooms.participants.subscribe-rules/list",
      "/twilio/video/rooms/rooms.participants.subscribed-tracks/list",
      "/twilio/video/rooms/rooms.participants.subscribed-tracks/read",
      "/twilio/video/rooms/rooms.participants/list",
      "/twilio/video/rooms/rooms.participants/read",
      "/twilio/video/rooms/rooms.recording-rules/list",
      "/twilio/video/rooms/rooms.recordings/list",
      "/twilio/video/rooms/rooms.recordings/read",
      "/twilio/video/rooms/rooms.transcriptions/list",
      "/twilio/video/rooms/rooms.transcriptions/read",
      "/twilio/video/rooms/rooms/list",
      "/twilio/video/rooms/rooms/read",
      "/twilio/voice/byoc-trunks/list",
      "/twilio/voice/byoc-trunks/read",
      "/twilio/voice/calls.notifications/list",
      "/twilio/voice/calls.notifications/read",
      "/twilio/voice/calls.recordings/list",
      "/twilio/voice/calls.recordings/read",
      "/twilio/voice/calls/list",
      "/twilio/voice/calls/read",
      "/twilio/voice/conferences.participants/list",
      "/twilio/voice/conferences.participants/read",
      "/twilio/voice/conferences.recordings/list",
      "/twilio/voice/conferences/list",
      "/twilio/voice/conferences/read",
      "/twilio/voice/connection-policies.targets/list",
      "/twilio/voice/connection-policies.targets/read",
      "/twilio/voice/connection-policies/list",
      "/twilio/voice/connection-policies/read",
      "/twilio/voice/insights.call.annotations/read",
      "/twilio/voice/insights.call.events/list",
      "/twilio/voice/insights.call.metrics/list",
      "/twilio/voice/insights.call.summaries/list",
      "/twilio/voice/insights.call.summaries/read",
      "/twilio/voice/insights.conference.participants/list",
      "/twilio/voice/insights.conference.participants/read",
      "/twilio/voice/insights.settings/read",
      "/twilio/voice/intelligence.operator-attachment/list",
      "/twilio/voice/intelligence.operators-results/read",
      "/twilio/voice/intelligence.operators-types/list",
      "/twilio/voice/intelligence.operators-types/read",
      "/twilio/voice/intelligence.operators.custom/list",
      "/twilio/voice/intelligence.operators.custom/read",
      "/twilio/voice/intelligence.operators.prebuilt/list",
      "/twilio/voice/intelligence.operators.prebuilt/read",
      "/twilio/voice/intelligence.operators/list",
      "/twilio/voice/intelligence.operators/read",
      "/twilio/voice/intelligence.services/list",
      "/twilio/voice/intelligence.services/read",
      "/twilio/voice/intelligence.transcript-media/read",
      "/twilio/voice/intelligence.transcript-sentences/read",
      "/twilio/voice/intelligence.transcripts/list",
      "/twilio/voice/intelligence.transcripts/read",
      "/twilio/voice/ip-records/list",
      "/twilio/voice/ip-records/read",
      "/twilio/voice/outgoing-caller-ids/list",
      "/twilio/voice/outgoing-caller-ids/read",
      "/twilio/voice/queues.member/list",
      "/twilio/voice/queues.member/read",
      "/twilio/voice/queues/list",
      "/twilio/voice/queues/read",
      "/twilio/voice/recordings.add-ons.payload.data/read",
      "/twilio/voice/recordings.add-ons.payload/list",
      "/twilio/voice/recordings.add-ons.payload/read",
      "/twilio/voice/recordings.add-ons/list",
      "/twilio/voice/recordings.add-ons/read",
      "/twilio/voice/recordings/list",
      "/twilio/voice/recordings/read",
      "/twilio/voice/request-inspector/read",
      "/twilio/voice/sip.credential-list-mappings/list",
      "/twilio/voice/sip.credential-list-mappings/read",
      "/twilio/voice/sip.credential-lists/list",
      "/twilio/voice/sip.credential-lists/read",
      "/twilio/voice/sip.domains.registrations.credential-list-mappings/list",
      "/twilio/voice/sip.domains.registrations.credential-list-mappings/read",
      "/twilio/voice/sip.domains/list",
      "/twilio/voice/sip.domains/read",
      "/twilio/voice/sip.ip-acl-mappings/list",
      "/twilio/voice/sip.ip-acl-mappings/read",
      "/twilio/voice/sip.ip-acls/list",
      "/twilio/voice/sip.ip-acls/read",
      "/twilio/voice/sip.ip-addresses/list",
      "/twilio/voice/sip.ip-addresses/read",
      "/twilio/voice/source-ip-mappings/list",
      "/twilio/voice/source-ip-mappings/read",
      "/twilio/voice/transcriptions/list",
      "/twilio/voice/transcriptions/read",
      "/twilio/voice/twiml.apps/read",
    ]
  }
}

ephemeral "local_command" "twilio_readonly_key" {
  command = "curl"
  arguments = [
    "-sS",
    "-X", "POST",
    "https://iam.twilio.com/v1/Keys",
    "--data-urlencode", "FriendlyName=monorepo-agent-readonly",
    "--data-urlencode", "AccountSid=${nonsensitive(data.infisical_secrets.ouroboros.secrets.TWILIO_API_KEY.value)}",
    "--data-urlencode", "KeyType=restricted",
    "--data-urlencode", "Policy=${jsonencode(local.twilio_readonly_policy)}",
    "-u", "${data.infisical_secrets.ouroboros.secrets.TWILIO_API_KEY.value}:${data.infisical_secrets.ouroboros.secrets.TWILIO_API_SECRET.value}",
  ]
}

# Twilio returns 4xx errors as a JSON body on stdout while curl -sS still exits 0,
# so without this gate the apply dies later with an opaque "no attribute named sid".
# Non-zero exit here fails the apply with Twilio's actual error body via stderr.
ephemeral "local_command" "twilio_readonly_key_check" {
  command = "python3"
  arguments = ["-c", <<-EOT
    import json, sys
    body = sys.stdin.read()
    try:
        resp = json.loads(body)
    except ValueError:
        sys.exit("Twilio /v1/Keys returned non-JSON response: " + body)
    if "sid" not in resp or "secret" not in resp:
        sys.exit("Twilio /v1/Keys error: " + body)
    sys.stdout.write(body)
  EOT
  ]
  stdin = ephemeral.local_command.twilio_readonly_key.stdout
}

locals {
  twilio_key_response = jsondecode(ephemeral.local_command.twilio_readonly_key_check.stdout)
}

resource "infisical_secret" "twilio_api_key" {
  name             = "TWILIO_API_KEY"
  value_wo         = local.twilio_key_response.sid
  value_wo_version = 3
  env_slug         = infisical_project_environment.global.slug
  workspace_id     = infisical_project.agent.id
  folder_path      = "/"
}

resource "infisical_secret" "twilio_api_secret" {
  name             = "TWILIO_API_SECRET"
  value_wo         = local.twilio_key_response.secret
  value_wo_version = 3
  env_slug         = infisical_project_environment.global.slug
  workspace_id     = infisical_project.agent.id
  folder_path      = "/"
}
